In [1]:
import matplotlib.pyplot as plt
import numpy as np


In [2]:
def create_mask_from_window(x):
    """
    Creates a mask from an input matrix x, to identify the max entry of x.
    
    Arguments:
    x -- Array of shape (f, f)
    
    Returns:
    mask -- Array of the same shape as window, contains a True at the position corresponding to the max entry of x.
    """
    
    ### START CODE HERE ### (≈1 line)
    mask = (x==np.max(x))
    ### END CODE HERE ###
    
    return mask

In [3]:
np.random.seed(1)
x = np.random.randn(2,3)

mask = create_mask_from_window(x)
x_maxPool = x * mask
print('x = ', x)
print("mask = ", mask)
print("x_maxPool = ", x_maxPool)

x =  [[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]]
mask =  [[ True False False]
 [False False False]]
x_maxPool =  [[ 1.62434536 -0.         -0.        ]
 [-0.          0.         -0.        ]]


In [4]:
def distribute_value(dz, shape):
    """
    Distributes the input value in the matrix of dimension shape
    
    Arguments:
    dz -- input scalar
    shape -- the shape (n_H, n_W) of the output matrix for which we want to distribute the value of dz
    
    Returns:
    a -- Array of size (n_H, n_W) for which we distributed the value of dz
    """
    
    ### START CODE HERE ###
    # Retrieve dimensions from shape (≈1 line)
    (n_H, n_W) = shape
    
    # Compute the value to distribute on the matrix (≈1 line)
    average = np.ones([n_H, n_W])
    
    # Create a matrix where every entry is the "average" value (≈1 line)
    a = dz*average/(n_H*n_W)
    ### END CODE HERE ###
    
    return a

In [5]:
def pool_forward(A_prev, hparameters, mode = "max"):
    """
    Implements the forward pass of the pooling layer
    
    Arguments:
    A_prev -- Input data, numpy array of shape (m, n_H_prev, n_W_prev, n_C_prev)
    hparameters -- python dictionary containing "f" and "stride"
    mode -- the pooling mode you would like to use, defined as a string ("max" or "average")
    
    Returns:
    A -- output of the pool layer, a numpy array of shape (m, n_H, n_W, n_C)
    cache -- cache used in the backward pass of the pooling layer, contains the input and hparameters 
    """
    (m, n_H_prev, n_W_prev, n_C_prev) = A_prev.shape
    f = hparameters.get('f')
    stride = hparameters.get('stride')
    
    n_H = int((n_H_prev-f)/stride+1)
    n_W = int((n_W_prev-f)/stride+1)
    n_C = n_C_prev
    
    A = np.zeros([m, n_H, n_W, n_C])
    
    for i in range(m):
        
        for h in range(n_H):
            vert_start = h * stride
            vert_end = vert_start + f
            
            for w in range(n_W):
                horiz_start = w * stride
                horiz_end = horiz_start + f
            
                for c in range(n_C):
                    a_slice_prev = A_prev[i, vert_start:vert_end, horiz_start:horiz_end, c]
                
                    if mode == 'max':
                        A[i, h, w, c] = np.max(a_slice_prev)
                    elif mode == 'average':
                        A[i, h, w, c] = np.average(a_slice_prev)
                    else:
                        print('modeError: string max or average is required')
    
    cache = (A_prev, hparameters)
    assert(A.shape == (m, n_H, n_W, n_C))
    
    return A, cache   

In [6]:
np.random.seed(1)
A_prev = np.random.randn(1, 4, 4, 1)
hparameters = {"stride" : 2, "f": 2}

print("A_prev = \n", str(A_prev))

A, cache = pool_forward(A_prev, hparameters)
print("mode = max")
print("A.shape = " + str(A.shape))
print("A =\n", A)
print()

A, cache = pool_forward(A_prev, hparameters, mode = "average")
print("mode = average")
print("A.shape = " + str(A.shape))
print("A =\n", A)

A_prev = 
 [[[[ 1.62434536]
   [-0.61175641]
   [-0.52817175]
   [-1.07296862]]

  [[ 0.86540763]
   [-2.3015387 ]
   [ 1.74481176]
   [-0.7612069 ]]

  [[ 0.3190391 ]
   [-0.24937038]
   [ 1.46210794]
   [-2.06014071]]

  [[-0.3224172 ]
   [-0.38405435]
   [ 1.13376944]
   [-1.09989127]]]]
mode = max
A.shape = (1, 2, 2, 1)
A =
 [[[[1.62434536]
   [1.74481176]]

  [[0.3190391 ]
   [1.46210794]]]]

mode = average
A.shape = (1, 2, 2, 1)
A =
 [[[[-0.10588553]
   [-0.15438388]]

  [[-0.15920071]
   [-0.14103865]]]]
